export const interest_mapping = {
    "I": [
        "authenticity",
        "creative writing",
        "daydreaming",
        "deep conversations",
        "emotional intelligence",
        "fantasy literature",
        "journaling",
        "literature",
        "mindfulness",
        "poetry",
        "reading",
        "self-discovery",
        "self-expression",
        "symbolism",
        "writing"
    ],
    "E": [
        "acting",
        "community service",
        "content creation",
        "debating",
        "event planning",
        "group activities",
        "hosting",
        "leadership",
        "networking",
        "parties",
        "performance arts",
        "public speaking",
        "sales and marketing",
        "socializing",
        "team building",
        "team coordination",
        "volunteering"
    ],
    "S": [
        "bookkeeping",
        "building and fixing",
        "cooking",
        "crafting",
        "documentaries",
        "docuseries",
        "engineering",
        "financial planning",
        "fitness",
        "history",
        "home decoration",
        "law and order",
        "mechanics",
        "motorcycles and cars",
        "organization",
        "repair",
        "routine",
        "security",
        "sports",
        "survival skills",
        "time management"
    ],
    "N": [
        "abstract thinking",
        "advocacy",
        "art",
        "creativity",
        "design",
        "entrepreneurship",
        "ethical philosophy",
        "future thinking",
        "individualism",
        "innovation",
        "inspiration",
        "mindfulness",
        "mythology",
        "new experiences",
        "personal growth",
        "philosophy",
        "psychology",
        "self-discovery",
        "spirituality",
        "storytelling",
        "symbolism"
    ],
    "T": [
        "AI",
        "algorithms",
        "analysis",
        "automation",
        "business strategy",
        "coding",
        "data analysis",
        "debate",
        "efficiency",
        "engineering",
        "goal-setting",
        "government and civics",
        "leadership development",
        "management",
        "organization",
        "physics",
        "planning",
        "problem solving",
        "productivity",
        "project management",
        "science",
        "strategy",
        "systems and logic",
        "technology"
    ],
    "F": [
        "caregiving",
        "community",
        "compassion",
        "counseling",
        "emotional intelligence",
        "emotional support",
        "empathy",
        "family",
        "friendship",
        "gratitude",
        "healing",
        "hospitality",
        "kindness",
        "mental health awareness",
        "psychotherapy",
        "relationships",
        "self-care",
        "social impact",
        "support",
        "tradition"
    ],
    "J": [
        "business strategy",
        "discipline",
        "efficiency",
        "financial planning",
        "goal-setting",
        "leadership",
        "leadership development",
        "management",
        "organization",
        "planning",
        "productivity",
        "project management",
        "risk management",
        "strategy",
        "time management"
    ],
    "P": [
        "adventure",
        "animals",
        "creativity",
        "fashion and beauty",
        "fun",
        "hobbies",
        "individualism",
        "learning",
        "music and dance",
        "natural beauty",
        "new experiences",
        "outdoors",
        "photography",
        "spontaneity",
        "travel",
        "trendspotting",
        "visual art"
    ]
}
