export const allInterests = [
    "abstract concepts",
    "abstract problem solving",
    "adventure",
    "analysis",
    "animals",
    "art and aesthetics",
    "art and design",
    "artificial intelligence",
    "authentic self-expression",
    "bookkeeping",
    "brainstorming ideas",
    "building and fixing",
    "business logistics",
    "business strategy",
    "business ventures",
    "caregiving",
    "coding and algorithms",
    "community leadership",
    "community organization",
    "community service",
    "competition",
    "complex games (e.g. chess, Go)",
    "conflict resolution",
    "content creation",
    "crafting",
    "creative problem solving",
    "creative writing",
    "data analysis",
    "data organization",
    "daydreaming",
    "debate",
    "documentaries",
    "docuseries",
    "DIY projects",
    "educating others",
    "education",
    "emerging technologies",
    "emotional expression",
    "emotional intelligence",
    "emotional support",
    "emotional support systems",
    "entertainment",
    "entrepreneurship",
    "ethical philosophy",
    "event hosting",
    "event organization",
    "event planning",
    "existential questions",
    "family and home life",
    "family leadership",
    "family traditions",
    "fast-paced environments",
    "fashion",
    "fashion and beauty",
    "finance",
    "financial management",
    "financial planning",
    "financial systems",
    "freedom of choice",
    "friendship building",
    "future forecasting",
    "government and civics",
    "group activities",
    "group dynamics",
    "hands-on creativity",
    "health and wellness",
    "historical accuracy",
    "historical fiction",
    "history",
    "home decoration",
    "hospitality",
    "human behavior",
    "improv and acting",
    "individual identity",
    "individualism",
    "independent action",
    "independent research",
    "independent study",
    "innovation",
    "intellectual challenges",
    "interior design",
    "journaling",
    "law and order",
    "learning new tools",
    "leadership",
    "leadership development",
    "life coaching",
    "literature",
    "living in the moment",
    "loyalty and service",
    "lifestyle aesthetics",
    "lifestyle design",
    "management",
    "martial arts",
    "marketing and branding",
    "mechanics",
    "mental health awareness",
    "mentorship",
    "motorcycles and cars",
    "motivational speaking",
    "music and dance",
    "music composition",
    "music with emotional depth",
    "mythology",
    "natural beauty",
    "nature and animals",
    "negotiation",
    "networking",
    "new experiences",
    "nonprofit work",
    "operational efficiency",
    "party planning",
    "personal development",
    "personal growth",
    "personal storytelling",
    "philosophical debates",
    "philosophy",
    "photography",
    "poetry",
    "practical challenges",
    "practical knowledge",
    "problem solving",
    "problem troubleshooting",
    "procedures and policies",
    "productivity systems",
    "project management",
    "project tracking",
    "psychology",
    "psychotherapy",
    "public speaking",
    "public relations",
    "quality assurance",
    "relationship psychology",
    "risk and reward",
    "risk management",
    "risk-taking",
    "routine-based hobbies",
    "sales and marketing",
    "science and technology",
    "self-expression",
    "social causes",
    "social dynamics",
    "social etiquette",
    "socializing",
    "spirituality",
    "sports",
    "sports coaching",
    "startup culture",
    "storytelling",
    "storytelling with morals",
    "strategic thinking",
    "structured debate",
    "survival skills",
    "symbolism",
    "systems and logic",
    "systems design",
    "tactical planning",
    "tactical strategy",
    "task completion",
    "teaching and caregiving",
    "team bonding",
    "team building",
    "team coordination",
    "technology gadgets",
    "technology trends",
    "time management",
    "tradition",
    "traditional knowledge",
    "traditional structures",
    "travel",
    "travel and cultures",
    "trendspotting",
    "volunteer work",
    "volunteering",
    "visual art",
    "vision planning",
    "woodworking",
    "writing",
    "writing and journaling",
    "writing inspirational content",
    "writing theory-based content"
  ];
  